# Generated by Django 5.1.5 on 2025-01-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_common',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
